import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="fr">
      <body className={`bg-white text-black`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
